# Generated by Django 3.1.3 on 2020-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phno', models.CharField(max_length=200, null=True)),
                ('emailid', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
