# Generated by Django 3.1.3 on 2020-11-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='typevn',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
