# Generated by Django 3.1.3 on 2020-11-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='C:/Users/Ivanka/Desktop/dbmsproject/static/images/dish/picn.jpeg', upload_to='gallery'),
        ),
    ]
