# Generated by Django 3.1.3 on 2021-01-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phno',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
