# Generated by Django 3.1.3 on 2021-01-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210102_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
