# Generated by Django 3.1.3 on 2021-01-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_order_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='tno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
