# Generated by Django 3.1.3 on 2021-01-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210102_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tno',
            new_name='Table_No',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='typevn',
        ),
    ]
