# Generated by Django 3.1.3 on 2021-01-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_clubmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('discount', models.FloatField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%')], null=True)),
                ('Table_No', models.CharField(max_length=10, null=True)),
                ('Club_Member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clubmember')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.menu')),
            ],
        ),
    ]
