# Generated by Django 3.1.3 on 2021-01-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cluborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluborder',
            name='discount',
            field=models.FloatField(choices=[('Ten', 'Ten'), ('Twenty', 'Twenty'), ('Thirty', 'Thirty')], null=True),
        ),
    ]
