# Generated by Django 3.1.3 on 2021-01-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210103_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluborder',
            name='discount',
        ),
    ]
